---
- name: Postgress on Ubuntu  Playbook
  hosts: postgress
  become: yes
  become_user: root
  tasks:
   - name: Update apt repo and cache on Ubuntu box
     apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

   - name: Upgrade all packages on servers
     apt:
      upgrade: dist
      force_apt_get: yes

   - name: Install wget
     apt:
      name: wget
      state: present

   - name: Install ca-certificat
     apt:
      name:  ca-certificates
      state: present
